### ISSUE TITLE
Signin Issue

### ISSUE THREAD

**Issue by ghost** [totaljs/example#1]
<img width="548" alt="screen shot 2016-01-03 at 8 05 45 pm" src="https://cloud.githubusercontent.com/assets/10177562/12081880/703f87a2-b255-11e5-8282-4b2cf5592c99.png">

[TypeError: Cannot read property 'collection' of null]
======= 2016-01-03 20:03:45: TypeError: Cannot read property 'collection' of null TypeError: Cannot read property 'collection' of null
at EventEmitter.F.database (/Users/toto/example-master/definitions/database.js:27:12)
at global.DB.global.DATABASE (/Users/toto/node_modules/total.js/index.js:213:28)
at SchemaBuilderEntity. (/Users/toto/example-master/models/users.js:84:18)
at /Users/toto/node_modules/total.js/builders.js:1961:13
at SchemaBuilderEntity.$prepare (/Users/toto/node_modules/total.js/builders.js:1296:3)
at SchemaBuilderEntity.workflow (/Users/toto/node_modules/total.js/builders.js:1946:7)
at /Users/toto/node_modules/total.js/builders.js:1216:9
at Array.async (/Users/toto/node_modules/total.js/utils.js:4252:2)
at Immediate._onImmediate (/Users/toto/node_modules/total.js/builders.js:1085:16)
at processImmediate as _immediateCallback
======= 2016-01-03 20:04:13: MongoError: connect ETIMEDOUT 54.155.29.65:35985 Error: connect ETIMEDOUT 54.155.29.65:35985
at Object.exports._errnoException (util.js:837:11)
at exports._exceptionWithHostPort (util.js:860:20)
at TCPConnectWrap.afterConnect as oncomplete

**Comment by ghost** [comment]
Works fine with my local DB
